services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-sqlite-viz
    user: "0:0"
    ports:
      - "3000:3000"
    volumes:
      - ./..:/mnt/data:ro
      - ./provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
      - GF_PLUGIN_FRSER_SQLITE_DATASOURCE_ALLOW_LOCAL_MODE=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_AUTH_BASIC_ENABLED=false
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: always
